apiVersion: v1
kind: Service
metadata:
  name: laravelio-service
spec:
  selector:
    app: laravelio
  ports:
    - protocol: TCP
      port: 80   # The port to access the service on
      targetPort: 8000   # The port your Laravel application is listening on
  type: LoadBalancer