---

- name: Refresh inventory
  meta: refresh_inventory

- name: Check that you can connect (GET) to App  and it returns a status 200
  ansible.builtin.uri:
    url: "http://{{ app_ip }}:{{app_port}}/"
    method: GET
    status_code: 200
  register: result
  until: result.status == 200
  retries: 3
  delay: 5